[package]
name = "claria-live-aws"
version = "0.15.0"
edition.workspace = true
license.workspace = true

[dependencies]
aws-config = "=1.8.16"
claria-provisioner = { path = "../claria-provisioner" }
jiff = { version = "=0.2.24", features = ["serde"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
specta = { version = "=2.0.0-rc.22", features = ["derive", "serde_json"] }
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", features = ["full"] }
tracing = "=0.1.44"
