// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async hasConfig() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadConfig() : Promise<Result<ConfigInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConfig(region: string, systemName: string, accountId: string, credentials: CredentialSource) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { region, systemName, accountId, credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConfig() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save one UI section's preference fields. Absent patch fields are left
 * untouched locally and in `_state/preferences.json`, so concurrent
 * sections can't clobber each other. Bubbles S3-write failures so the
 * frontend can show a partial-save warning.
 */
async savePreferencesPatch(patch: PreferencesPatch) : Promise<Result<ConfigInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences_patch", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-fetch synced preferences from S3 and overlay onto the in-memory config.
 * Used by the Preferences page on entry so users on the editing machine see
 * the latest cloud state without an app restart.
 */
async fetchCloudPreferences() : Promise<Result<ConfigInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_cloud_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upload an audio file and transcribe with the wizard's per-file options.
 * 
 * Same skeleton as [`upload_record_file`], but restricted to audio and with
 * a fatal sidecar: the wizard exists to produce a transcript, so a failed
 * transcription fails the command instead of degrading to a warning.
 */
async uploadRecordFileWithOptions(clientId: string, filePath: string, overrides: TranscribeOptionsOverrides | null) : Promise<Result<RecordFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_record_file_with_options", { clientId, filePath, overrides }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save edits to the transcript sidecar. S3 versioning preserves every prior
 * body, including the Transcribe-generated v1 — clinicians restore any past
 * version (or the original) via the standard `list_file_versions` /
 * `restore_file_version` flow, which the frontend routes to the `.text`
 * sidecar for audio files.
 */
async saveTranscriptEdits(clientId: string, filename: string, body: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_transcript_edits", { clientId, filename, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a native file picker scoped to supported audio formats. Returns the
 * absolute path the user chose, or `None` if they cancelled.
 * 
 * Used by the transcription wizard so we can keep a real file picker on the
 * wizard surface (avoiding the geometry-sensitive drag-target controls flagged
 * in [feedback-ui-low-dexterity]).
 */
async pickAudioFile() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_audio_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the clinician's preferred chat model.
 * 
 * Loads the current config, updates `preferred_model_id`, and saves. Pass
 * `None` to clear the preference (fall back to the first available model).
 * 
 * `preferred_model_id` is part of [`SyncedPreferences`], and `load_config`
 * overlays that S3 copy onto the local config on every call. Writing only the
 * local file would therefore be undone by the very next `load_config` — the
 * pick would survive on disk but the app would keep reading the stale cloud
 * value. The cloud write is not optional for this field.
 */
async setPreferredModel(modelId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_preferred_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assess the provided credentials: validates them via STS and classifies
 * them as root / IAM admin / scoped Claria / insufficient.
 * 
 * The desktop app uses the returned `CredentialAssessment` to decide
 * which UI flow to present (bootstrap vs. straight to provisioning).
 */
async assessCredentials(region: string, credentials: CredentialInput) : Promise<Result<CredentialAssessment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assess_credentials", { region, credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Assume a role in an AWS sub-account using parent-account credentials.
 * 
 * The operator provides their parent-account credentials and the sub-account
 * details. We call STS AssumeRole, hold the temporary credentials in memory,
 * and return an [`AssumedRoleSession`] whose handle later provisioning
 * commands exchange for them. Neither the secret access key nor the session
 * token ever reaches the frontend, and nothing is persisted to disk.
 */
async assumeRole(region: string, credentials: CredentialInput, accountId: string, roleName: string) : Promise<Result<AssumedRoleSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("assume_role", { region, credentials, accountId, roleName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAwsProfiles() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_aws_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all access keys for the `claria-admin` IAM user, enriched with
 * last-used metadata.
 * 
 * Called when bootstrap fails due to the 2-key limit so the operator can
 * pick which key to delete.
 */
async listUserAccessKeys(region: string, credentials: CredentialInput) : Promise<Result<AccessKeyInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_user_access_keys", { region, credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete one access key belonging to the `claria-admin` IAM user.
 * 
 * Called after the operator picks a key to remove to make room for a
 * fresh one during bootstrap.
 */
async deleteUserAccessKey(region: string, credentials: CredentialInput, accessKeyId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_user_access_key", { region, credentials, accessKeyId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the full bootstrap flow: create a scoped IAM user and policy using
 * the operator's current (broad) credentials, then persist the new scoped
 * credentials to the local config.
 * 
 * The provisioner does all the IAM work and returns the new credentials.
 * We handle only the config write and in-memory state update.
 */
async bootstrapIamUser(region: string, systemName: string, rootAccessKeyId: string, rootSecretAccessKey: string, sessionToken: string | null, credentialClass: CredentialClass) : Promise<Result<BootstrapOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bootstrap_iam_user", { region, systemName, rootAccessKeyId, rootSecretAccessKey, sessionToken, credentialClass }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the `ClariaProvisionerAccess` IAM policy using temporary elevated
 * credentials (root or admin).
 * 
 * The dashboard calls this when the manifest changes and requires IAM actions
 * not in the current policy. The elevated credentials are used once and
 * discarded — they are never persisted to disk.
 */
async escalateIamPolicy(accessKeyId: string, secretAccessKey: string, onProgress: TAURI_CHANNEL<ProvisionerProgress>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("escalate_iam_policy", { accessKeyId, secretAccessKey, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan all resources using the provided credentials.
 * 
 * This is the entry point for both first-run and day-2 flows. On first run
 * the frontend passes the user's initial credentials; on day-2 the frontend
 * passes the saved scoped credentials (or calls `plan()` instead).
 * 
 * Returns a `ProvisionScanResult` that tells the frontend whether elevated
 * credentials are needed before applying.
 */
async provisionScan(region: string, systemName: string, credentials: CredentialInput, onProgress: TAURI_CHANNEL<ProvisionerProgress>) : Promise<Result<ProvisionScanResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("provision_scan", { region, systemName, credentials, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply all changes in one unified reconciliation.
 * 
 * Two-phase execution:
 * 1. If elevated resources need changes and `elevated_credentials` is provided,
 * execute elevated resources first (IAM user, policy).
 * 2. After elevated execution, create an access key for the claria-admin user
 * if no config exists yet (credential handoff from admin → scoped creds).
 * 3. Execute regular resources with the scoped credentials.
 * 4. Re-scan and return the updated plan.
 * 
 * Step 2 can hit IAM's two-access-key ceiling when the account has already
 * onboarded two computers. That is reported as
 * [`ProvisionApplyOutcome::access_key_limit`] so the caller can offer key
 * deletion and retry.
 */
async provisionApply(region: string, systemName: string, credentials: CredentialInput, elevatedCredentials: CredentialInput | null, onProgress: TAURI_CHANNEL<ProvisionerProgress>) : Promise<Result<ProvisionApplyOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("provision_apply", { region, systemName, credentials, elevatedCredentials, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan all resources and return an annotated plan.
 * 
 * Streams `ProvisionerProgress` events via the channel as each resource
 * is scanned. Scans up to 5 resources concurrently for speed.
 */
async plan(onProgress: TAURI_CHANNEL<ProvisionerProgress>) : Promise<Result<PlanEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plan", { onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute all actionable entries in the plan.
 * 
 * Returns the updated plan (all entries should now be Ok).
 * Streams `ProvisionerProgress` events via the channel as each resource
 * is created/modified/deleted.
 */
async apply(onProgress: TAURI_CHANNEL<ProvisionerProgress>) : Promise<Result<PlanEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply", { onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Destroy all managed resources with temporary elevated credentials.
 *
 * The saved scoped credentials deliberately cannot erase S3 version history.
 * The supplied root or IAM administrator credentials are validated against
 * the configured account, used only for this teardown, and never persisted.
 */
async destroy(elevatedCredentials: CredentialInput) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("destroy", { elevatedCredentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the provisioner state file (local + S3) so the next scan starts fresh.
 * 
 * Use this when state is incompatible with the current version of Claria.
 * AWS resources are not affected — the next scan will re-discover them.
 */
async resetProvisionerState() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_provisioner_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all client records from S3.
 * 
 * Loads each `clients/{id}.json` object, deserializes the Client, and
 * returns summaries sorted by most recently created first.
 */
async listClients() : Promise<Result<ClientSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_clients") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new client record in S3.
 */
async createClient(name: string) : Promise<Result<ClientSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_client", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load editable metadata, storage statistics, and name history for one client.
 */
async getClientRecordDetails(clientId: string) : Promise<Result<ClientRecordDetails, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_client_record_details", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a client's display name with optimistic concurrency control.
 */
async updateClientName(clientId: string, name: string) : Promise<Result<ClientNameUpdate, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_client_name", { clientId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a client and all associated data through the retryable,
 * compensating lifecycle library.
 */
async deleteClient(clientId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_client", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startReportWorkspace(clientId: string, reportId: string) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_report_workspace", { clientId, reportId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadReportWorkspace(clientId: string, reportId: string) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_report_workspace", { clientId, reportId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return every persisted Writing session for the Record screen's Editor
 * History folder without creating a new workspace.
 */
async listEditorHistory(clientId: string) : Promise<Result<EditorHistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_editor_history", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameReportSession(clientId: string, reportId: string, name: string) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_report_session", { clientId, reportId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listReportRevisions(clientId: string, reportId: string) : Promise<Result<ReportRevisionView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_report_revisions", { clientId, reportId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadReportRevision(clientId: string, reportId: string, revision: number) : Promise<Result<ReportDraft, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_report_revision", { clientId, reportId, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revertReportRevision(clientId: string, reportId: string, expectedRevision: number, revision: number) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_report_revision", { clientId, reportId, expectedRevision, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveReportDraft(clientId: string, reportId: string, expectedRevision: number, draft: ReportDraftEdit) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_report_draft", { clientId, reportId, expectedRevision, draft }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardQueuedReportEdits(clientId: string, reportId: string, expectedRevision: number) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_queued_report_edits", { clientId, reportId, expectedRevision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWriterTemplates() : Promise<Result<WriterTemplateView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_writer_templates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pick, validate, and upload a redacted DOCX into the managed template shelf.
 * The local filename and path are never persisted.
 */
async uploadWriterTemplate() : Promise<Result<WriterTemplateView | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_writer_template") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameWriterTemplate(templateId: string, name: string) : Promise<Result<WriterTemplateView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_writer_template", { templateId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteWriterTemplate(templateId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_writer_template", { templateId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Parse a managed template into an in-memory candidate for direct application.
 */
async previewWriterTemplate(clientId: string, templateId: string) : Promise<Result<ReportTemplatePreview, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_writer_template", { clientId, templateId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a parsed managed DOCX candidate as a new accepted revision.
 */
async applyReportTemplate(clientId: string, reportId: string, expectedRevision: number, importId: string) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_report_template", { clientId, reportId, expectedRevision, importId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardReportTemplatePreview(importId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_report_template_preview", { importId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateFullReport(clientId: string, reportId: string, expectedRevision: number, modelId: string, guidance: string, onProgress: TAURI_CHANNEL<ReportTurnProgressView>) : Promise<Result<FullReportGenerationResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_full_report", { clientId, reportId, expectedRevision, modelId, guidance, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendReportMessage(clientId: string, reportId: string, expectedRevision: number, modelId: string, instruction: string, references: ReportBlockReferenceInput[], onProgress: TAURI_CHANNEL<ReportTurnProgressView>) : Promise<Result<ReportTurnResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_report_message", { clientId, reportId, expectedRevision, modelId, instruction, references, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveReportProposal(clientId: string, reportId: string, proposalId: string, decision: ReportProposalChoice) : Promise<Result<ReportWorkspaceView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_report_proposal", { clientId, reportId, proposalId, decision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportReportDocx(clientId: string, reportId: string, expectedRevision: number) : Promise<Result<ReportExportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_report_docx", { clientId, reportId, expectedRevision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List files in a client's record, excluding sidecar `.text` files.
 * 
 * `prefix` narrows the listing to filenames starting with it, mapped to the
 * S3 ListObjectsV2 `Prefix` parameter (`records/{id}/{prefix}`).
 */
async listRecordFiles(clientId: string, prefix: string | null) : Promise<Result<RecordFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_record_files", { clientId, prefix }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Filenames in a client's record whose readable text contains `query`,
 * case-insensitively.
 */
async searchRecordContents(clientId: string, query: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_record_contents", { clientId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upload a file to a client's record from a local file path.
 * 
 * Printable UTF-8 files remain directly readable under their original names.
 * PDF and DOCX files receive a structured-Markdown `.text` sidecar via
 * Bedrock; audio files receive a transcript sidecar. Sidecar generation
 * failure degrades to a warning — the original upload has already succeeded.
 */
async uploadRecordFile(clientId: string, filePath: string) : Promise<Result<RecordFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_record_file", { clientId, filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a file from a client's record, including its generated sidecar
 * when present.
 */
async deleteRecordFile(clientId: string, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_record_file", { clientId, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the readable text for a record file.
 * 
 * Generated document/transcript sidecars take precedence. Otherwise any
 * printable UTF-8 original—including JSON, Markdown, CSV, and extensionless
 * text—is returned unchanged.
 */
async getRecordFileText(clientId: string, filename: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_record_file_text", { clientId, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a plain text file in a client's record.
 * 
 * Writes the given content as a `.txt` file directly to S3. If the filename
 * doesn't already end in `.txt`, it is appended.
 */
async createTextRecordFile(clientId: string, filename: string, content: string) : Promise<Result<RecordFile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_text_record_file", { clientId, filename, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update the content of an existing plain text file in a client's record.
 */
async updateTextRecordFile(clientId: string, filename: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_text_record_file", { clientId, filename, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load text content for all record files belonging to a client.
 * 
 * Printable UTF-8 originals are returned unchanged, regardless of extension.
 * PDF, DOCX, and audio files use their generated `.text` sidecars. Files with
 * no safe readable representation are omitted.
 */
async listRecordContext(clientId: string) : Promise<Result<RecordContext[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_record_context", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve readable text for a single record file.
 * 
 * PDF and DOCX files are re-extracted through Bedrock, audio is
 * retranscribed, and printable UTF-8 originals are returned unchanged.
 */
async extractRecordFile(clientId: string, filename: string) : Promise<Result<RecordContext, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_record_file", { clientId, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List available Anthropic Claude models for chat.
 * 
 * Queries Bedrock for system-defined inference profiles and returns
 * those matching Anthropic Claude models.
 */
async listChatModels() : Promise<Result<ChatModel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a chat message to Bedrock and return the assistant's response.
 * 
 * The frontend maintains the full conversation history and sends it
 * with each request so the model has context. The system prompt is
 * fetched from S3 on each call so edits take effect immediately.
 * Record context (text from the client's files) is loaded from S3
 * and prepended to the system prompt.
 * 
 * After each successful exchange, the full conversation is persisted
 * to S3 under `records/{client_id}/chat-history/{chat_id}.json`.
 * The `chat_id` is generated on the first message and returned so the
 * frontend can pass it back on subsequent calls.
 */
async chatMessage(clientId: string, modelId: string, messages: ChatMessage[], chatId: string | null, chatName: string | null, contextFilenames: string[], onEvent: TAURI_CHANNEL<ChatStreamEvent>) : Promise<Result<ChatResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_message", { clientId, modelId, messages, chatId, chatName, contextFilenames, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Chat about infrastructure — no history persistence.
 * 
 * The frontend passes pre-scanned `plan_entries` so we don't re-scan AWS
 * on every message. We build a rich system prompt explaining Claria's
 * operating model and the current infrastructure state, then call Bedrock.
 */
async infraChat(modelId: string, messages: ChatMessage[], planEntries: PlanEntry[], onEvent: TAURI_CHANNEL<ChatStreamEvent>) : Promise<Result<InfraChatResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("infra_chat", { modelId, messages, planEntries, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Accept the Marketplace agreement for a Bedrock foundation model.
 * 
 * Called when a model requires an agreement before it can be used.
 * The frontend can detect this from the error message and offer
 * a one-click accept flow.
 */
async acceptModelAgreement(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("accept_model_agreement", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List named chat sessions for the Record screen history folder.
 */
async listChatHistories(clientId: string) : Promise<Result<ChatHistorySummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_histories", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a chat history session from S3.
 * 
 * Returns the full conversation with model ID so the frontend can
 * resume the session in the Chat widget.
 */
async loadChatHistory(clientId: string, chatId: string) : Promise<Result<ChatHistoryDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_chat_history", { clientId, chatId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a persisted chat session without changing its stable UUID key.
 */
async renameChatHistory(clientId: string, chatId: string, name: string) : Promise<Result<ChatHistoryDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_chat_history", { clientId, chatId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current content of a named prompt.
 * 
 * Returns the custom prompt from S3 if one exists, otherwise returns the
 * built-in default. Valid prompt names: `"system-prompt"`, `"pdf-extraction"`.
 */
async getPrompt(promptName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt", { promptName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save a named prompt to S3.
 * 
 * Overwrites any previously saved version. The new content takes effect on
 * the next operation that uses this prompt.
 */
async savePrompt(promptName: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { promptName, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a named prompt from S3, reverting to the built-in default.
 */
async deletePrompt(promptName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { promptName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all versions of a named prompt stored in S3.
 */
async listPromptVersions(promptName: string) : Promise<Result<FileVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_prompt_versions", { promptName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the text content of a specific version of a named prompt.
 */
async getPromptVersion(promptName: string, versionId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_prompt_version", { promptName, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a previous version of a named prompt by writing it as the new current version.
 */
async restorePromptVersion(promptName: string, versionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_prompt_version", { promptName, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all versions of a specific file in a client's record.
 */
async listFileVersions(clientId: string, filename: string) : Promise<Result<FileVersion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_file_versions", { clientId, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the text content of a specific version of a file.
 */
async getFileVersionText(clientId: string, filename: string, versionId: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_version_text", { clientId, filename, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a previous version of a file by copying its content to a new PUT.
 */
async restoreFileVersion(clientId: string, filename: string, versionId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_file_version", { clientId, filename, versionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List deleted files in a client's record (files with a delete marker).
 */
async listDeletedFiles(clientId: string) : Promise<Result<DeletedFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_deleted_files", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a deleted file by re-putting the most recent real version as a new version.
 * 
 * This preserves the full version history (including the delete marker) for
 * HIPAA audit-trail compliance, instead of removing the delete marker.
 * Delegates to the storage crate's conditional restore, so a concurrent
 * re-upload of the same filename is never overwritten.
 */
async restoreDeletedFile(clientId: string, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_deleted_file", { clientId, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List deleted clients (client JSON files with a delete marker).
 */
async listDeletedClients() : Promise<Result<DeletedClient[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_deleted_clients") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a deleted client by re-putting the most recent real version as a new version.
 * 
 * This preserves the full version history (including the delete marker) for
 * HIPAA audit-trail compliance, instead of removing the delete marker.
 */
async restoreClient(clientId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_client", { clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLocalTranscriptionStatus() : Promise<Result<LocalTranscriptionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_transcription_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveLocalTranscriptionSettings(settings: LocalTranscriptionSettings) : Promise<Result<LocalTranscriptionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_local_transcription_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadLocalModel(modelId: LocalModelId, onProgress: TAURI_CHANNEL<ModelDownloadProgress>) : Promise<Result<LocalTranscriptionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_local_model", { modelId, onProgress }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLocalModel(modelId: LocalModelId) : Promise<Result<LocalTranscriptionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_local_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteLegacyTranscriptionModels() : Promise<Result<LocalTranscriptionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_legacy_transcription_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcribeMemo(audioPcmBase64: string) : Promise<Result<TranscribeMemoResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_memo", { audioPcmBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check whether a newer release exists on GitHub.
 * 
 * Hits the GitHub releases API and compares `tag_name` against the compiled-in
 * version. On any failure (network, parse) returns `update_available: false` so
 * the UI never errors out.
 */
async checkForUpdates() : Promise<Result<UpdateCheck, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCostAndUsage(startDate: string, endDate: string, granularity: CostGranularity, groupByService: boolean) : Promise<Result<CostAndUsageResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cost_and_usage", { startDate, endDate, granularity, groupByService }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeCostExplorer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_cost_explorer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enableCostExplorer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_cost_explorer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHourlyCostData(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_hourly_cost_data", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Look up `ModelPricing` for a Bedrock model_id. Returns `None` for
 * unknown models so the UI can hide pre-flight estimates rather than
 * show `$NaN`.
 */
async lookupModelPricing(modelId: string) : Promise<Result<ModelPricing | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_model_pricing", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openUrl(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the application's log folder in the OS file manager, creating it if
 * file logging has not produced anything yet.
 */
async revealLogFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_log_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countClientContextTokens(clientId: string, contextFilenames: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_client_context_tokens", { clientId, contextFilenames }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async countInfraContextTokens(planEntries: PlanEntry[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("count_infra_context_tokens", { planEntries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Console entries at or after the sequence cursor `seq`. Pass the previous
 * response's `next_seq`; start (or force a full refetch) with `0`.
 */
async getConsoleLogsSince(seq: number) : Promise<ConsoleDelta> {
    return await TAURI_INVOKE("get_console_logs_since", { seq });
},
async getConsoleLogsText() : Promise<string> {
    return await TAURI_INVOKE("get_console_logs_text");
},
async saveConsoleLogs() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_console_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Record a frontend-reported event into the shared tracing stack.
 * 
 * The `claria_desktop::frontend` target is admitted by the console and file
 * layers via the shared crate-list filter, so webview failures land in the
 * ring buffer and the rolling on-disk logs. Messages are length-capped and
 * stripped of control characters so one event cannot flood the buffer or
 * forge multi-line log records. Callers report operation names and error
 * strings — never document content or client names.
 */
async logFrontendEvent(level: FrontendLogLevel, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend_event", { level, message });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Metadata for an existing IAM access key.
 * 
 * Returned by [`list_user_access_keys`] so the operator can decide which
 * key to delete when the IAM 2-key limit is reached.
 */
export type AccessKeyInfo = { 
/**
 * The access key ID (e.g. `AKIA...`).
 */
access_key_id: string; 
/**
 * `"Active"` or `"Inactive"`.
 */
status: string; 
/**
 * When the key was created (ISO 8601).
 */
created_at: string | null; 
/**
 * When the key was last used (ISO 8601), or `None` if never used.
 */
last_used_at: string | null; 
/**
 * The AWS service the key was last used with (e.g. `"s3"`, `"iam"`),
 * or `None` if never used.
 */
last_used_service: string | null }
/**
 * Why the credential handoff could not mint a key for this computer.
 * 
 * IAM caps a user at two access keys, so onboarding a third machine against
 * an already-provisioned account is a routine outcome, not a crash. The
 * frontend uses this to offer key deletion instead of dead-ending.
 */
export type AccessKeyLimitReached = { 
/**
 * The IAM user whose key slots are full.
 */
user_name: string; 
/**
 * How many keys AWS allows.
 */
limit: number; 
/**
 * The full error text, so the operator sees exactly what AWS said.
 */
message: string }
export type Action = "ok" | "create" | "modify" | "delete" | "precondition_failed"
/**
 * What `assume_role` returns to the frontend: everything about the assumed
 * session except its secrets, plus the opaque handle later provisioning
 * commands exchange for them.
 */
export type AssumedRoleSession = { 
/**
 * Opaque reference to the credentials held in memory.
 */
handle: string; 
/**
 * Temporary access key ID (not secret; shown for operator recognition).
 */
access_key_id: string; 
/**
 * When the temporary credentials expire (ISO 8601).
 */
expiration: string | null; 
/**
 * The ARN of the assumed role.
 */
assumed_role_arn: string; 
/**
 * The account ID of the sub-account we assumed into.
 */
account_id: string }
/**
 * Redacted [`BootstrapResult`] for the frontend: the minted secret access
 * key is persisted to the local config Rust-side and never returned.
 */
export type BootstrapOutcome = { success: boolean; steps: BootstrapStep[]; account_id: string | null; 
/**
 * Present when bootstrap minted scoped credentials.
 */
new_credentials: NewCredentialsInfo | null; error: string | null }
/**
 * A single step in the bootstrap sequence, reported for UI rendering.
 */
export type BootstrapStep = { name: string; status: StepStatus; detail: string | null }
/**
 * Time-to-live for a Bedrock prompt-cache entry.
 * 
 * Lives next to the capability table because which TTLs a model accepts is
 * model knowledge: `FiveMinutes` is the server default every caching model
 * supports, while `OneHour` requires
 * [`ModelCapabilities::supports_extended_cache_ttl`]. Persisted on
 * `TurnUsage` so historical costs price cache writes at the rate that was
 * actually in effect.
 */
export type CacheTtlChoice = "five_minutes" | "one_hour"
/**
 * Identity information returned by STS `GetCallerIdentity`.
 */
export type CallerIdentity = { account_id: string; arn: string; user_id: string; is_root: boolean }
export type Cause = "in_sync" | "missing" | "drift" | "orphaned"
/**
 * Detail of a persisted chat session, returned when resuming a conversation.
 */
export type ChatHistoryDetail = { chat_id: string; name: string; model_id: string; messages: ChatHistoryDetailMessage[]; created_at: string; updated_at: string }
/**
 * A single message in persisted chat history, including optional token
 * usage on assistant turns.
 */
export type ChatHistoryDetailMessage = { role: ChatRole; content: string; timestamp: string;
/**
 * `Some` on assistant turns whose Converse response carried a usage
 * block. `None` on user turns and on assistant turns from history
 * written before per-turn usage tracking landed.
 */
usage: TurnUsage | null }
/**
 * Lightweight persisted-chat row for the Record screen history folder.
 */
export type ChatHistorySummary = { chat_id: string; filename: string; name: string; size: number; updated_at: string }
/**
 * One conversation turn — role plus text content. Shared by the Bedrock
 * chat call and the desktop IPC surface so the two cannot drift.
 */
export type ChatMessage = { role: ChatRole; content: string }
/**
 * Specta type mirroring `claria_bedrock::chat::ChatModel`.
 */
export type ChatModel = { model_id: string; name: string }
/**
 * Response from a chat message, including the persisted chat session ID
 * and per-turn token usage. Usage is `None` when Bedrock omitted the usage
 * block — the UI renders absence instead of a fabricated zero.
 */
export type ChatResponse = { chat_id: string; chat_name: string; content: string; usage: TurnUsage | null }
/**
 * Role of a chat message — the one role enum shared by persisted history,
 * the Bedrock chat calls, and the desktop IPC surface.
 */
export type ChatRole = "user" | "assistant"
/**
 * One increment of a streaming chat response, sent over the command's
 * channel while the model responds. The command still returns the complete
 * response, so a caller that ignores the channel (tests, mocks) loses
 * nothing but the incremental render.
 */
export type ChatStreamEvent = 
/**
 * Incremental assistant text.
 */
{ kind: "delta"; text: string } | 
/**
 * Terminal event: the model finished; usage and stop reason are final.
 */
{ kind: "done"; stop_reason: string; usage: TurnUsage | null }
export type ClientNameHistoryEntry = { name: string; changed_at: string }
export type ClientNameUpdate = { id: string; name: string; updated_at: string }
export type ClientRecordDetails = { id: string; name: string; created_at: string; updated_at: string; file_count: number; storage_bytes: number; storage_bytes_with_history: number; name_history: ClientNameHistoryEntry[] }
export type ClientSummary = { id: string; name: string; created_at: string }
/**
 * Redacted config info safe to send to the frontend.
 */
export type ConfigInfo = { region: string; system_name: string; account_id: string; created_at: string; credential_type: string; profile_name: string | null; access_key_hint: string | null; preferred_model_id: string | null; cost_explorer_enabled: boolean; hourly_cost_data: boolean; prompt_caching_enabled: boolean; transcription: TranscriptionPreferences; report_authoring: ReportAuthoringPreferences }
/**
 * One poll's worth of new console entries, addressed by a monotonic
 * sequence cursor so the 500ms UI poll ships only new lines.
 */
export type ConsoleDelta = { entries: ConsoleEntry[]; 
/**
 * Cursor to pass on the next poll.
 */
next_seq: number; 
/**
 * True when `entries` is the full buffer and must replace, not append —
 * the requested cursor predates the buffer (lines rotated out unseen)
 * or came from a previous app run.
 */
reset: boolean }
/**
 * A single log entry captured by the console ring buffer.
 */
export type ConsoleEntry = { timestamp: string; level: string; target: string; message: string }
export type CostAndUsageResult = { periods: CostTimePeriod[] }
export type CostGranularity = "hourly" | "daily" | "monthly"
export type CostResultGroup = { key: string; amount: string; unit: string }
export type CostTimePeriod = { start: string; end: string; groups: CostResultGroup[] }
/**
 * The result of `assess_credentials`.
 */
export type CredentialAssessment = { identity: CallerIdentity; credential_class: CredentialClass; 
/**
 * Human-readable explanation of why this class was chosen.
 */
reason: string }
/**
 * Classification of the credentials the operator provided.
 */
export type CredentialClass = 
/**
 * The AWS account root user. Has God-mode access but should never be
 * used for day-to-day operations. Bootstrap required.
 */
"root" | 
/**
 * An IAM principal (user or role) with broad permissions — at minimum
 * the ability to manage IAM users and policies. Bootstrap required to
 * create a scoped Claria user.
 */
"iam_admin" | 
/**
 * An IAM principal that already has the minimal Claria permissions.
 * Ready for resource provisioning.
 */
"scoped_claria" | 
/**
 * The credentials lack the permissions Claria needs and also lack the
 * IAM permissions required to self-bootstrap.
 */
"insufficient"
/**
 * Credentials as the frontend supplies them to provisioning commands.
 * 
 * Mirrors [`CredentialSource`] for the user-typed variants and adds
 * `AssumedRole`, an opaque handle to temporary STS credentials held in
 * [`DesktopState`] — the secret access key and session token from an
 * `assume_role` call never cross the IPC boundary.
 */
export type CredentialInput = { type: "inline"; access_key_id: string; secret_access_key: string; session_token?: string | null } | { type: "profile"; profile_name: string } | { type: "default_chain" } | { type: "assumed_role"; handle: string }
export type CredentialScope = 
/**
 * Requires elevated credentials (root/admin) to create or modify.
 * Can be read with regular (claria-admin) credentials for drift detection.
 */
"elevated" | 
/**
 * Uses the regular claria-admin credentials.
 */
"regular"
export type CredentialSource = { type: "inline"; access_key_id: string; secret_access_key: string; session_token?: string | null } | { type: "profile"; profile_name: string } | { type: "default_chain" }
/**
 * A client that has been deleted (has a delete marker on the client JSON).
 */
export type DeletedClient = { id: string; name: string; deleted_at: string | null; version_id: string }
/**
 * A file that has been deleted (has a delete marker as the latest version).
 */
export type DeletedFile = { filename: string; deleted_at: string | null; version_id: string }
export type EditorHistoryEntry = { report_id: string; name: string; title: string; revision: number; turn_count: number; updated_at: string; last_export: ReportExport | null }
/**
 * Structured before/after for a single field that doesn't match desired state.
 * 
 * Returned by `ResourceSyncer::diff()`. The frontend renders these directly
 * as before/after rows.
 */
export type FieldDrift = { 
/**
 * Machine-readable field name, e.g. "sse_algorithm"
 */
field: string; 
/**
 * Human-readable label, e.g. "Encryption algorithm"
 */
label: string; 
/**
 * What we want
 */
expected: JsonValue; 
/**
 * What AWS has
 */
actual: JsonValue }
/**
 * A single version of a file in a client's record.
 */
export type FileVersion = { version_id: string; size: number; last_modified: string | null; is_latest: boolean }
/**
 * Severity levels the frontend logging bridge may report.
 */
export type FrontendLogLevel = "error" | "warn" | "info"
export type FullReportGenerationResponse = { workspace: ReportWorkspaceView; turn_id: string; attempt_id: string; assistant_text: string; usage: TurnUsage; usage_complete: boolean; converse_calls: number; tool_uses: number; included_record_files: number; unavailable_record_files: number; record_characters: number }
/**
 * Response from an infrastructure chat turn. Infra chat does not persist
 * history, but we still return token usage so the UI can display cost.
 * Usage is `None` when Bedrock omitted the usage block.
 */
export type InfraChatResponse = { content: string; usage: TurnUsage | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Lifecycle = "data" | "managed"
export type LocalBackend = "auto" | "cpu" | "cpu_accel" | "metal" | "vulkan" | "cuda" | "rocm"
export type LocalBackendInfo = { backend: LocalBackend; label: string; available: boolean }
export type LocalComputeDevice = { name: string; description: string; kind: string; device_type: string; device_id: string | null; memory_total: number; memory_free: number; index: number | null }
export type LocalKvPrecision = "auto" | "f32" | "f16"
export type LocalModelId = "whisper_base_en_q8" | "whisper_small_q8" | "whisper_turbo_q8"
export type LocalModelInfo = { id: LocalModelId; label: string; description: string; filename: string; quantization: string; languages: string[]; download_size_bytes: number; downloaded: boolean; model_size_bytes: number | null; model_path: string | null; active: boolean }
export type LocalTranscriptionSettings = { settings_version: number; speech_model: LocalModelId; backend: LocalBackend; gpu_device: number; cpu_threads: number; kv_precision: LocalKvPrecision; initial_prompt: string; condition_on_previous_text: boolean; max_previous_context_tokens: number; temperature: number; temperature_increment: number; compression_ratio_threshold: number; log_probability_threshold: number; no_speech_threshold: number; seed: number }
export type LocalTranscriptionStatus = { runtime_version: string; settings: LocalTranscriptionSettings; models: LocalModelInfo[]; backends: LocalBackendInfo[]; devices: LocalComputeDevice[]; legacy_model_bytes: number; accelerated: boolean }
export type ModelDownloadProgress = { model_id: LocalModelId; downloaded_bytes: number; total_bytes: number }
/**
 * Pricing per million tokens for a Bedrock model.
 * 
 * Cache fields cover Anthropic-on-Bedrock prompt caching:
 * - `cache_read_per_million` — typically ~10% of `input_per_million`.
 * - `cache_write_per_million` — typically ~125% of `input_per_million`
 * for the 5-minute TTL tier.
 * - `cache_write_1h_per_million` — typically ~200% of `input_per_million`
 * for the extended 1-hour TTL tier.
 */
export type ModelPricing = { input_per_million: number; output_per_million: number; cache_read_per_million: number; cache_write_per_million: number; 
/**
 * `#[serde(default)]` so pricing serialized before the 1-hour tier
 * existed still deserializes; an absent (0.0) rate falls back to the
 * 5-minute write rate rather than pricing 1-hour writes at zero.
 */
cache_write_1h_per_million?: number }
/**
 * The non-secret half of freshly minted credentials.
 */
export type NewCredentialsInfo = { access_key_id: string; iam_user_arn: string }
/**
 * A single entry in the plan — the spec annotated with what happened.
 * 
 * The plan is a flat `Vec<PlanEntry>` — same shape as the manifest array,
 * annotated with status. The entry embeds the full spec so the frontend
 * has everything it needs (label, description, severity, desired state)
 * without a separate lookup.
 */
export type PlanEntry = { spec: ResourceSpec; action: Action; cause: Cause; drift: FieldDrift[]; 
/**
 * Live state read from AWS (if the resource exists).
 */
actual: JsonValue | null }
/**
 * Named-field patch for the synced preferences. Absent fields are left
 * untouched, so a UI section (or a single-setting command) saves only what
 * it owns and can never roll back a sibling section's edit.
 */
export type PreferencesPatch = { 
/**
 * `Some(Some(id))` sets the preferred model, `Some(None)` clears it
 * (only expressible in-process — over IPC use `set_preferred_model`),
 * `None` leaves it unchanged.
 */
preferred_model_id?: string | null; cost_explorer_enabled?: boolean | null; hourly_cost_data?: boolean | null; prompt_caching_enabled?: boolean | null; transcription?: TranscriptionPreferences | null; report_authoring?: ReportAuthoringPreferences | null }
/**
 * What `provision_apply` did.
 * 
 * Reconciliation normally ends with a fresh plan. The one recoverable
 * interruption is the IAM access-key ceiling during the first-run credential
 * handoff, which is reported here rather than as an opaque error string.
 */
export type ProvisionApplyOutcome = { 
/**
 * The post-apply plan. Empty when `access_key_limit` is set.
 */
entries: PlanEntry[]; 
/**
 * Set when the handoff stopped at the IAM two-key ceiling.
 */
access_key_limit: AccessKeyLimitReached | null }
/**
 * Result of a provision scan. Contains everything the frontend needs to
 * render the plan and decide whether escalation is required.
 */
export type ProvisionScanResult = { 
/**
 * The full plan across all resources.
 */
entries: PlanEntry[]; 
/**
 * True if any `Elevated`-scope resource needs Create or Modify,
 * meaning the user must provide admin/root credentials.
 */
needs_escalation: boolean; 
/**
 * The account ID (resolved via STS from the provided credentials).
 */
account_id: string }
export type ProvisionerProgress = { kind: "scan_started"; label: string; index: number; total: number } | { kind: "scan_completed"; label: string; index: number; total: number } | { kind: "apply_started"; label: string; action: string; index: number; total: number } | { kind: "apply_completed"; label: string; action: string; index: number; total: number } | { kind: "escalation_step"; label: string; status: string }
/**
 * A record file with its readable text content, for chat context.
 */
export type RecordContext = { filename: string; text: string }
/**
 * A file in a client's record (S3 object metadata).
 */
export type RecordFile = { filename: string; size: number; uploaded_at: string | null }
/**
 * Per-clinician guardrails for agentic document writing. These values sync
 * across machines. The report-authoring crate validates the
 * relationship between the limits before they are saved or used.
 */
export type ReportAuthoringPreferences = { max_tool_rounds?: number; max_converse_calls?: number; max_tool_uses_per_response?: number; max_retained_turns?: number }
export type ReportAuthoringTurnView = { id: string; model_id: string; timeline: ReportTimelineItemView[]; usage: TurnUsage; usage_complete: boolean; converse_calls: number; tool_uses: number;
/**
 * Records preloaded outside the model's record-reading tools. Only the
 * filename and availability cross IPC; source hashes/counts stay in the
 * durable workspace and record text is never persisted there.
 */
context_files: ReportContextFileView[]; context_reads: ReportContextReadView[]; created_at: string; completed_at: string }
export type ReportBlock = { kind: "paragraph"; text: string } | { kind: "bullet_list"; items: string[] } | 
/**
 * A rectangular, plain-text table. The first row is rendered as a
 * semantic header when `has_header` is true. Optional widths are basis
 * points whose sum is exactly 10,000 (100%).
 */
{ kind: "table"; rows: string[][]; has_header: boolean; column_widths?: number[] | null }
export type ReportBlockReferenceInput = { section_id: string; block_index: number }
export type ReportContent = { title: string; sections: ReportSection[] }
export type ReportContextFileView = { filename: string; available: boolean }
export type ReportContextReadView = { filename: string; offset: number; returned_characters: number; total_characters: number | null; read_at: string }
export type ReportDraft = { revision: number; content: ReportContent; created_at: string; updated_at: string; last_applied_proposal_id: string | null }
export type ReportDraftEdit = { title: string; sections: ReportSectionEdit[] }
export type ReportExport = { revision: number; status: ReportExportStatus; attempted_at: string }
export type ReportExportResult = { exported: boolean; report_id: string; revision: number; status: ReportExportStatus; attempted_at: string; status_persisted: boolean }
export type ReportExportStatus = "exported" | "canceled" | "failed"
export type ReportOperation = { kind: "set_title"; title: string } | { kind: "add_section"; position: number; section: ReportSection } | { kind: "replace_section"; section_id: string; heading: string; blocks: ReportBlock[] } | { kind: "remove_section"; section_id: string }
/**
 * Earns its life next to `ReportProposalDecision`: this is the imperative
 * request wire shape (`accept`/`reject`), not the stored past-tense
 * resolution (`accepted`/`rejected`).
 */
export type ReportProposalChoice = "accept" | "reject"
export type ReportProposalDecision = "accepted" | "rejected"
export type ReportProposalResolution = { proposal_id: string; decision: ReportProposalDecision; resulting_revision: number; resolved_at: string }
/**
 * Earns its life over `ReportProposal`: omits `tool_use_id`, the internal
 * Bedrock correlation handle the frontend has no business seeing.
 */
export type ReportProposalView = { id: string; report_id: string; base_revision: number; model_id: string; summary: string; operations: ReportOperation[]; proposed_content: ReportContent; created_at: string }
export type ReportRevisionView = { revision: number; title: string; updated_at: string }
export type ReportSection = { id: string; heading: string; blocks: ReportBlock[] }
export type ReportSectionEdit = { id: string | null; heading: string; blocks: ReportBlock[] }
export type ReportTemplateImportView = { writer_template_id: string | null; writer_template_name: string | null; imported_revision: number; imported_at: string; warnings: ReportTemplateWarningView[]; reviewed_revision: number | null; review_required: boolean; placeholder_count: number }
export type ReportTemplatePreview = { import_id: string; content: ReportContent; warnings: ReportTemplateWarningView[]; stats: ReportTemplateStatsView }
export type ReportTemplateStatsView = { sections: number; paragraphs: number; bullet_lists: number; tables: number; table_cells: number; placeholder_count: number }
export type ReportTemplateWarningView = { code: string; message: string; count: number }
export type ReportTimelineItemView = { kind: "message"; role: ReportTimelineRole; text: string; created_at: string } | { kind: "tool_activity"; name: string; summary: string; status: ReportToolActivityStatus; invocation_json: string; result_json: string | null; created_at: string }
export type ReportTimelineRole = "user" | "assistant"
export type ReportToolActivityStatus = "requested" | "succeeded" | "failed"
export type ReportTurnProgressView = { kind: "record_context_prepared"; included_files: number; unavailable_files: number; total_characters: number } | { kind: "model_call_started"; call_number: number } | { kind: "tool_started"; name: string; context: string | null } | { kind: "tool_finished"; name: string; context: string | null; status: ReportToolActivityStatus }
export type ReportTurnResponse = { workspace: ReportWorkspaceView; turn_id: string; attempt_id: string; assistant_text: string; usage: TurnUsage; usage_complete: boolean; converse_calls: number; tool_uses: number; proposal_id: string | null }
/**
 * Earns its life over `ReportWorkspace`: flattens the session container and
 * replaces raw turns with derived timeline/context views.
 */
export type ReportWorkspaceView = { schema_version: number; report_id: string; client_id: string; session_name: string; draft: ReportDraft; turns: ReportAuthoringTurnView[]; pending_proposal: ReportProposalView | null; resolutions: ReportProposalResolution[]; last_agent_revision: number | null; last_export: ReportExport | null; template_import: ReportTemplateImportView | null; created_at: string; updated_at: string }
/**
 * Every resource in the system is declared as a `ResourceSpec`.
 * 
 * The spec carries both the desired AWS state and the trust metadata
 * (label, description, severity, required IAM actions). This is the
 * single source of truth — the syncer, the plan, and the UI all read
 * from it.
 */
export type ResourceSpec = { 
/**
 * e.g. "s3_bucket", "baa_agreement"
 */
resource_type: string; 
/**
 * e.g. "123456789012-claria-data"
 */
resource_name: string; 
/**
 * Data (read-only precondition) or Managed (Claria creates/updates/deletes)
 */
lifecycle: Lifecycle; 
/**
 * The desired AWS state as a JSON value — shape varies per resource type
 */
desired: JsonValue; 
/**
 * Which credential scope this resource belongs to
 */
credential_scope: CredentialScope; 
/**
 * Short label for the UI, e.g. "S3 Bucket Encryption"
 */
label: string; 
/**
 * Human-readable purpose, e.g. "Server-side encryption — your data is encrypted at rest"
 */
description: string; 
/**
 * How much attention this entry needs
 */
severity: Severity; 
/**
 * IAM actions this resource requires (aggregated for policy diff)
 */
iam_actions: string[] }
export type Severity = 
/**
 * Data sources — read-only checks
 */
"info" | 
/**
 * Routine infra (S3 settings, CloudTrail)
 */
"normal" | 
/**
 * Requires acknowledgment (BAA, model agreements)
 */
"elevated" | 
/**
 * Data loss risk (bucket deletion during orphan cleanup)
 */
"destructive"
export type SpeakerMode = "none" | "diarize" | "channels"
/**
 * Status of an individual bootstrap step.
 */
export type StepStatus = "pending" | "in_progress" | "succeeded" | "failed"
export type TAURI_CHANNEL<TSend> = null
export type TranscribeMemoResult = { text: string; language: string | null; model_id: LocalModelId; backend: string }
/**
 * Per-file overrides for the wizard flow. Each field is optional so the
 * frontend only sends what the user actually changed; everything else falls
 * back to the saved preferences. Uses the `TranscriptionLanguage` type from
 * our config crate (specta-typed) rather than the library's `LanguageMode` —
 * the wrapper keeps the TS binding inside the desktop crate's surface.
 */
export type TranscribeOptionsOverrides = { language?: TranscriptionLanguage | null; speaker_mode?: SpeakerMode | null; speaker_count?: number | null; use_medical_for_english?: boolean | null; 
/**
 * When set, overrides `prefs.translate_to_english` for this single file.
 */
translate_to_english?: boolean | null }
export type TranscriptionLanguage = "english" | "spanish" | "mixed"
/**
 * Per-clinician defaults for the transcription pipeline.
 * 
 * These flow into both the drag-and-drop fast path (used as-is) and the wizard
 * (pre-filled, user may override per-file). They sync across the clinician's
 * machines via the [`SyncedPreferences`] mechanism.
 */
export type TranscriptionPreferences = { default_language?: TranscriptionLanguage; default_speaker_count?: number; 
/**
 * When true, English-only sessions route to Transcribe Medical (3x cost,
 * clinical-vocabulary tuning, PHI tagging). Spanish and Mixed sessions
 * always use Standard.
 */
use_medical_for_english?: boolean; 
/**
 * When true, segments whose detected language is not English get an
 * English translation rendered alongside the original via Bedrock.
 * Default off — the primary user is bilingual; future users may want it.
 */
translate_to_english?: boolean }
/**
 * Per-turn token usage captured from a Bedrock Converse response.
 * 
 * Cache fields are populated by the prompt-caching layer; until then they
 * are `0`, which the UI must treat as "no caching active", not "missing
 * data". `String` field means this type cannot be `Copy`.
 */
export type TurnUsage = { 
/**
 * Inference profile ID actually invoked (e.g.
 * `us.anthropic.claude-sonnet-4-20250514-v1:0`). Stored per-turn — not
 * inherited from `ChatHistory.model_id` — because the user can switch
 * models mid-session and we want each turn priced against the model
 * that produced it.
 */
model_id: string; 
/**
 * Non-cached input tokens billed at full rate.
 */
input_tokens: number; 
/**
 * Output tokens billed at output rate.
 */
output_tokens: number; 
/**
 * Cache-hit input tokens (Anthropic-on-Bedrock cache read). Mirrors the
 * AWS SDK `TokenUsage::cache_read_input_tokens`. `0` when prompt
 * caching is not active.
 */
cache_read_input_tokens: number; 
/**
 * Cache-write input tokens — the first turn that creates the cache
 * entry. Mirrors the AWS SDK `TokenUsage::cache_write_input_tokens`.
 * `0` when prompt caching is not active.
 */
cache_write_input_tokens: number; 
/**
 * TTL carried by the request's cache points. `None` means the
 * 5-minute default or a legacy/uncached turn — either way cache
 * writes billed at the 5-minute rate, so absence prices correctly.
 */
cache_ttl?: CacheTtlChoice | null; 
/**
 * USD cost computed at the moment of the call against `pricing_version`.
 * Frozen — never recomputed on read. UI may recompute live for
 * "what-if" estimates but must keep this value as the audit-of-record.
 */
cost_usd: number; 
/**
 * Version of the pricing table used to compute `cost_usd`. Bumped each
 * time `claria-billing::pricing` is edited. `0` means "unknown /
 * pre-versioning".
 */
pricing_version: number }
/**
 * Result of checking for a newer release on GitHub.
 */
export type UpdateCheck = { current_version: string; latest_version: string; update_available: boolean; release_url: string }
export type WriterTemplateView = { id: string; name: string; size: number; uploaded_at: string; use_count: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
