[package]
name = "claria-storage"
version = "0.18.0"
edition.workspace = true
license.workspace = true

[dependencies]
aws-config = "=1.8.16"
aws-sdk-s3 = "=1.132.0"
aws-smithy-types = "=1.4.7"
claria-core = { path = "../claria-core" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", features = ["full"] }
tracing = "=0.1.44"

[dev-dependencies]
aws-credential-types = "=1.2.14"
claria-mock-aws = { path = "../claria-mock-aws" }
uuid = { version = "=1.23.1", features = ["v4"] }
