[package]
name = "claria-storage"
version = "0.19.0"
edition.workspace = true
license.workspace = true

[dependencies]
aws-config = "=1.8.18"
aws-sdk-s3 = "=1.137.0"
aws-smithy-types = "=1.5.0"
claria-core = { path = "../claria-core" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", features = ["full"] }
tracing = "=0.1.44"

[dev-dependencies]
aws-credential-types = "=1.2.14"
bytes = "=1.12.0"
claria-mock-aws = { path = "../claria-mock-aws" }
uuid = { version = "=1.23.4", features = ["v4"] }
